name: psp-dynamic-libraries
 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pspdev/pspdev
    steps:
      - name: Dependencies
        run: |
          apk add clang automake autoconf zlib-dev python3 py3-pycryptodomex py3-ecdsa zip sudo

      - name: Clone integrated PSPSDK fork
        run: |
          git clone --depth 1 --branch dev/fork --recurse-submodules --shallow-submodules https://github.com/StochasticEagle/pspsdk.git

      - name: Build and install PSPSDK
        working-directory: pspsdk
        run: |
          bash ./bootstrap
          ./configure
          make -j "$(getconf _NPROCESSORS_ONLN)"
          make install
          ./build-cfw-and-install.sh

      - name: ya2d via psp-pacman
        run: |
          psp-pacman -Syyu --noconfirm
          psp-pacman -S ya2d --noconfirm

      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Build
        run: make clean && make

      - name: Compress
        run: |
          cd dist/LIBS
          zip -r ../../LIBS.zip .

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: psp-dynamic-libraries-release
          path: LIBS.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: psp-dynamic-libraries-release
          path: .

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: psp-dynamic-libraries
          prerelease: false
          files: LIBS.zip
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
